language: generic

git:
  depth: 5

matrix:
  include:

# ShellCheck tests on generator and sh, ksh, bash dist files
  - env:
      - task=shellcheck
    script:
      - shellcheck -x generator.sh
  - env:
      - task=shellcheck-dist-sh
    script:
      - shellcheck dist/ColorEcho.sh
  - env:
      - task=shellcheck-dist-ksh
    script:
      - shellcheck dist/ColorEcho.ksh
  - env:
      - task=shellcheck-dist-bash
    script:
      - shellcheck dist/ColorEcho.bash

# test all echo functions on difference shell(except sh, which is actually bash) on Mac
  - os: osx
    env:
      - task=test-dist-zsh
    before_script:
      - brew install zsh
      - type zsh && zsh --version
    script:
      - ./test-scripts/zsh
  - os: osx
    env:
      - task=test-dist-ksh
    before_script:
      - brew install ksh
      - type ksh && ksh --version || printf ""
    script:
      - ./test-scripts/ksh
  - os: osx
    env:
      - task=test-dist-bash-builtin
    before_script:
      - type bash && bash --version
    script:
      - ./test-scripts/bash
  - os: osx
    env:
      - task=test-dist-bash-brew-install
      - PATH="/usr/local/bin/:$PATH"
    before_script:
      - brew install bash
      - type bash && bash --version
    script:
      - ./test-scripts/bash
  - os: osx
    env:
      - task=test-dist-fish
    before_script:
      - brew install fish
      - type fish && fish --version
    script:
      - ./test-scripts/fish

# test all echo functions on difference shell on Linux
  - env:
      - task=test-dist-sh
    script:
      - ./test-scripts/sh
  - env:
      - task=test-dist-zsh
    addons:
      apt:
        packages:
          - zsh
    before_script:
      - type zsh && zsh --version
    script:
      - ./test-scripts/zsh
  - env:
      - task=test-dist-ksh
    addons:
      apt:
        packages:
          - ksh
    before_script:
      - type ksh && ksh --version || printf ""
    script:
      - ./test-scripts/ksh
  - env:
      - task=test-dist-bash
    before_script:
      - type bash && bash --version
    script:
      - ./test-scripts/bash
  - env:
      - task=test-dist-fish
    addons:
      apt:
        packages:
          - fish
    before_script:
      - type fish && fish --version
    script:
      - ./test-scripts/fish
