language: generic

git:
  depth: 1

matrix:
  include:

  - os: osx
    env:
      - task=test-dist-bash-brew-install
      - PATH="/usr/local/bin/:$(echo $PATH | sed 's/::/:/')"
    before_script:
      - brew install bash
      - type bash && bash --version
    script:
      - ./test-scripts/bash
