#!/usr/bin/env sh

set -e
dir="$(cd "$(dirname "$_")" && pwd)"
script="${dir}/../dist/ColorEcho.sh"
. "${script}"

for x in $(grep -E "echo[a-zA-Z]+()" "${script}" | sed 's/()//g')
do
    $x "$x"
done
