#!/usr/bin/env zsh

set -e
dir="$(cd "$(dirname "${(%):-%N}")" && pwd)"
script="${dir}/../dist/ColorEcho.zsh"
. "${script}"

for x in $(awk '/^function +echo/ {print $2}' "${script}")
do
    $x "$x"
done
